### ISSUE TITLE
Redesign Rules Screen

### ISSUE THREAD

**Issue by moconn68** [moconn68/depic#11]
The rules screen, as it exists, is fairly unappealing. I slapped it together quickly just to have something to put there that technically works, but it needs a basic overhaul. If you look at it for a few moments you'll see what I mean, but just to list a few things:

+ Reduce the number of words on screen
+ Find a way (different font/color/background image) to make the words more legible
+ Incorporate a legend for the icons used in the app (check ./assets/art/ for their locations in-app)

**Comment by jhuang1998** [comment]
fix it!
