### ISSUE TITLE
Fix High Score System

### ISSUE THREAD

**Issue by moconn68** [moconn68/depic#9]
The current high score mechanism is malfunctioning. The method used to add new scores in their appropriate order (by rank) does so improperly. To see this in action, play the game a few times and save your high scores with different names. You will begin to notice that most of your attempts will get saved twice in two different places.

Fixing this will likely require reworking of most of the existing code for the insertion methodology in place now, but that logic isn't too expansive. Make sure to carefully examine existing code & comments to ensure that the little details aren't broken when implementing this fix.

**Comment by DymonSimone** [comment]
issue fixed

**Comment by moconn68** [comment]
See PR comments

**Comment by moconn68** [comment]
Resolved in [d6ebd20](https://github.com/moconn68/depic/commit/d6edb20f3e90d6ddb1fb21970d9ef1569ac53510)
